export const projects = [
  {
    id: 1,
    title: "Shoper",
    image: "public/Project/shoper.png",
    github: "https://github.com/rahebkarokhil/ShoppereCommerce-Temlate-Byraheb",
    vercel: "https://shoppere-commerce-temlate-busniss.vercel.app/",

  },
  {
    id: 2,
    title: "Play",
    image: "public/Project/play.png",
    github: "https://github.com/rahebkarokhil/portfolio",
    vercel: "https://portfolio.vercel.app",
  },
  {
    id: 3,
    title: "Suntower",
    image: "public/Project/suntower.png",
    github: "https://github.com/rahebkarokhil/Suntower",
    vercel: "https://suntower-rtua.vercel.app/",
  },
  {
    id: 4,
    title: "Adi-Plus medical Complix",
    image: "public/Project/Adiplus.png",
    github: "https://github.com/rahebkarokhil/adi-medical",
    vercel: "https://adi-medical.vercel.app",
  },
  {
    id: 5,
    title: "Tailwind CSS",
    image: "public/Project/tailwind.png",
    github: "https://github.com/rahebkarokhil/portfolio1",
    vercel: "https://portfolio1.vercel.app",
  },
  {
    id: 6,
    title: "Portfolio 2",
    image: "public/Demo/7946bd215836435.67754c6270bad.jpg",
    github: "https://github.com/rahebkarokhil/portfolio2",
    vercel: "https://portfolio2.vercel.app",
  },
  {
    id: 7,
    title: "Portfolio 3",
    image: "../public/Demo/888794166692497.641c62c108d8c (1).jpg",
    github: "https://github.com/rahebkarokhil/portfolio3",
    vercel: "https://portfolio3.vercel.app",
  },
  {
    id: 8,
    title: "Portfolio 4",
    image: "/public/Demo/b27fe3153262673.632c59ad439a8 (1).jpg",
    github: "https://github.com/rahebkarokhil/portfolio4",
    vercel: "https://portfolio4.vercel.app",
  },
  {
    id: 9,
    title: "Portfolio 5",
    image: "../public/Demo/c66e97190910979.65c28392cbf24.jpg",
    github: "https://github.com/rahebkarokhil/portfolio5",
    vercel: "https://portfolio5.vercel.app",
  },
  {
    id: 10,
    title: "Portfolio 6",
    image: "../public/Demo/d08ab2181515409.651d59b243be0.jpg",
    github: "https://github.com/rahebkarokhil/portfolio6",
    vercel: "https://portfolio6.vercel.app",
  },
  {
    id: 11,
    title: "Portfolio 7",
    image: "../public/Demo/d476e3168046461.643410e10beac.jpg",
    github: "https://github.com/rahebkarokhil/portfolio7",
    vercel: "https://portfolio7.vercel.app",
  },
];
